### ISSUE TITLE
Cache operator install in e2e CI

### ISSUE THREAD

**Issue by gjermundgaraba** [srdtrk/solidity-ibc-eureka#37]
The e2e tests in CI currently spend 10 minutes to install the operator binary. If there are no changes in the `cosmos/sp1-ics07-tendermint` repo, it would be ideal to cache the binary. 

Perhaps we can either check the latest commit, or keep the rust build cache somehow (so that a build with no changes are really fast).

**Comment by srdtrk** [comment]
Seems like [this](https://github.com/Swatinem/rust-cache) can be used?

**Comment by srdtrk** [comment]
We can use a combination of [this](https://github.com/actions/cache/blob/main/examples.md#rust---cargo) and [this](https://github.com/actions/cache?tab=readme-ov-file#skipping-steps-based-on-cache-hit)
